### ISSUE TITLE
Print clippy version for sanity checking

### ISSUE THREAD

**Issue by Nemo157** [crate-ci/meta#17]
For sanity's sake I'd also recommend adding `cargo clippy --version` to the install step to remove any doubts of the cache not being invalidated when the version number is updated.

**Comment by epage** [comment]
> for sanity's sake I'd also recommend adding cargo clippy --version to the install step to remove any doubts of the cache not being invalidated when the version number is updated.

At least on Travis, this should not be needed because `CLIPPY_VERSION` is an environment variable and Travis wipes the cache on environment variable change.  Things were a lot uglier / harder to maintain until we came across that piece of documentation.

**Comment by Nemo157** [comment]
> At least on Travis, this should not be needed

Yes, I would hope it never is actually needed. But when you’re in the middle of trying to track down why a commit is failing on CI but works locally it’s nice to have the tools explicitly log their version numbers. It’s purely a psychological trick to reassure you that every thing is working as intended.

**Comment by epage** [comment]
Ok, you're recommendation is to just print the version like [we do with rustc / cargo](https://github.com/crate-ci/example-clippy/blob/master/.travis.yml#L18) and not do any validation tricks?

I dropped doing that  in these cases because it was explicit but if its a helpful sanity check, sure, we can add it back in.  I'm splitting this out into a separate issue though.

**Comment by Nemo157** [comment]
> Ok, you're recommendation is to just print the version like we do with rustc / cargo and not do any validation tricks?

Yep, exactly.

**Comment by epage** [comment]
Not needed now that clippy is a rustup component.
