### ISSUE TITLE
Indent example YML lists with 2 spaces

### ISSUE THREAD

**Issue by chippers** [crate-ci/meta#23]
In the examples at https://crate-ci.github.io/ the YML lists in examples do not use indentation for travis-ci (and 1 AppVeyor).

```yml
rust:
- stable
- beta
- nightly
```

The official Travis CI documentation uses 2 spaces for indenting lists, and so do the official rust lang and cargo `.travis.yml`.  Keeping this consistent in our examples could help any confusion from YML's lax formatting rules, and other projects/documentation for travis.

```yml
rust:
  - stable
  - beta
  - nightly
```

**Comment by epage** [comment]
Oh, sorry I wasn't clear.  For something superficial like this, it would just be an issue on the docs / examples.  This space is meant for more policy decision making.

As for this, I really don't care.  I didn't do the extra indentation because `- ` makes the hierarchy clear and avoids having deep indentation.
