### ISSUE TITLE
Remove redundant version checking for Travis CI

### ISSUE THREAD

**Issue by chippers** [crate-ci/meta#24]
At https://crate-ci.github.io/ examples with Travis CI, there is often advice to add the following to `.travis.yml`.

```yml
install:
- rustc -Vv
- cargo -V
```
> - `install`: print tool versions for traceability

This results in output similar to:
```bash
chip@dev:~$ rustc -Vv
rustc 1.29.1 (b801ae664 2018-09-20)
binary: rustc
commit-hash: b801ae66425cf7c3c71052b19ef8f145b0d0513d
commit-date: 2018-09-20
host: x86_64-unknown-linux-gnu
release: 1.29.1
LLVM version: 7.0
chip@dev:~$ cargo -V
cargo 1.29.0 (524a578d7 2018-08-05)
```

However, in Travis CI it will print these versions by default without prompting (including the start of the commit hash for rustc like cargo's).  These are shown at the top of the job build due to the previous items automatically collapsing.

![travis](https://user-images.githubusercontent.com/3301043/46847254-3607bd00-cd98-11e8-9c32-c16b6cb4fe26.PNG)

Is having these extra install commands worth it, when the same functionality is present with a smaller example config?

**Comment by epage** [comment]
Eh, if its already there, then its fine to drop.  I think I added it at a time when I was noting the version of cached `cargo install` tools. I've since changed how I handle the caching of those.  When adding those versions, I think I added these "for good measure" without noticing they are already there.
